### ISSUE TITLE
Build Jar Error.

### ISSUE THREAD

**Issue by ZSYMAX** [Liubsyy/JarEditor#16]
Save的时候是OK的,对应的temp目录下class文件也生成了，但是Build Jar的时候报错了，win10系统，插件版本是2.1.3.
是需要什么特殊操作吗？我试过了管理员启动idea,还是一样的报错

Build jar err: Build jar failed: java.io.FileNotFoundException: D:\Java\vm_smt862\jar_edit\jarEdit\jars\ExecutionTree.jar (拒绝访问。) at java.base/java.io.FileOutputStream.open0(Native Method) at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293) at java.base/java.io.FileOutputStream. (FileOutputStream.java:235) at java.base/java.io.FileOutputStream. (FileOutputStream.java:123) at com.liubs.jareditor.jarbuild.JarBuilder.writeTargetJar(JarBuilder.java:273) at com.liubs.jareditor.jarbuild.JarBuilder.writeJar(JarBuilder.java:71) at com.liubs.jareditor.editor.JarEditorCore$2.run(JarEditorCore.java:229) at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428) at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251) at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679) at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173) at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699) at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Liubsyy** [comment]
没有特殊操作，看着像跟权限有关系，jar换个路径试试

**Comment by ZSYMAX** [comment]
我之前是旗舰版不行，换了社区版可以了
