### ISSUE TITLE
写入Jar包失败

### ISSUE THREAD

**Issue by ZhuBoyang** [Liubsyy/JarEditor#2]
<img width="1828" alt="image" src="https://github.com/Liubsyy/JarEditor/assets/36301761/8eb9eb69-f1d7-47ec-b791-a29c2a93c52f">
我增加了一行代码，按照流程点击 SAVE，然后点击 BUILD JAR，消息提示我 Build successfully，但是实际上并没有写入到 Jar 包里

**Comment by Liubsyy** [comment]
编译失败了，依赖com.intellij.openapi的包找不到，你应该是编译一个IDEA插件的jar，需要IntelliJ Platform Plugin SDK的依赖包，最简单的办法就是添加SDK，目录选IDEA的安装目录

<img width="649" alt="image" src="https://github.com/Liubsyy/JarEditor/assets/132696548/3b172be0-ce72-43f9-a0f8-f3a11eadb787">


然后在Project中设置SDK，这样依赖包就都过来了 ( 也可以手动添加Libraries），最后用SDK Default去编译即可

![image](https://github.com/Liubsyy/JarEditor/assets/132696548/5fc71c19-27ba-4c66-b974-897a324c58aa)

**Comment by ZhuBoyang** [comment]
添加 SDK 这一步，需要使用社区版打开么，因为我在 Ultimate Edition 版里只看到了 add jdk

**Comment by ZhuBoyang** [comment]
我使用社区版打开了，修改了代码，但是在 Save 的时候，就报错了。没有找到 javac，但是我已经引入 SDK 了
<img width="1436" alt="image" src="https://github.com/Liubsyy/JarEditor/assets/36301761/2dead880-beb5-4895-9414-d9e2b6c7e45b">

**Comment by Liubsyy** [comment]
本质上编译失败的原因是没有com.intellij.openapi的包，所以有两种方案：
1. 在Project Structure->Libraries中添加IntelliJ Platform Plugin SDK中的jar，包括lib/下和plugins/java/lib下的，然后用JDK17以上（IDEA2023 SDK的jar是java17的，可以选SDK Default默认就是用IDEA启动的JDK）
2. 我上面说的方案，把Project Structure->Project->SDK设置为IntelliJ Platform Plugin SDK，这种方式本质上还是添加依赖包，编译的时候可以选SDK Default（不要选IntelliJ Platform Plugin SDK）

**Comment by ZhuBoyang** [comment]
搞定了，非常感谢

**Comment by Liubsyy** [comment]
下个版本优化下，选定SDK后，自动添加SDK目录下的jar到classpath参与编译
